//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef_fundamentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENTE
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<int> ID_SEXO { get; set; }
    
        public virtual SEXO SEXO { get; set; }
    }
}
